// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghpnplsphhymuvfbtbug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdocG5wbHNwaGh5bXV2ZmJ0YnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTk3MDgsImV4cCI6MjA2NTU3NTcwOH0.RfWTo8WA1G-iBfeOglPs3Mhg3KYSWCQXz7txMslKgVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);